export enum EXPENSE_TYPE {
  DINING = 1,
  TRANSPORT = 2,
  ENTERTAINMENT = 3,
  PARKING = 4,
  SHOPPING = 5,
  CLOTHING = 6,
  MISC = 7,
  GROCERIES = 8,
  HOUSING = 9,
  UTILITIES = 10,
  INTERNET = 11,
  PHONE = 12,
  HEALTHCARE = 13,
  INSURANCE = 14,
  SUBSCRIPTIONS = 15,
  TRAVEL = 16,
  GIFTS = 17,
  FEES = 18,
  ELECTRONICS = 19,
  HOBBIES = 20,
}

export enum EXPENSE_TYPE_STATUS {
  VALID = 1,
  INVALID,
}

export const verifyExpenseType = (expenseType: number): EXPENSE_TYPE_STATUS => {
  if (Object.values(EXPENSE_TYPE).includes(expenseType)) {
    return EXPENSE_TYPE_STATUS.VALID;
  }
  return EXPENSE_TYPE_STATUS.INVALID;
};

export const convertToExpenseType = (expenseType: number): string => {
  switch (expenseType) {
    case EXPENSE_TYPE.DINING:
      return EXPENSE_TYPE[EXPENSE_TYPE.DINING];
    case EXPENSE_TYPE.TRANSPORT:
      return EXPENSE_TYPE[EXPENSE_TYPE.TRANSPORT];
    case EXPENSE_TYPE.ENTERTAINMENT:
      return EXPENSE_TYPE[EXPENSE_TYPE.ENTERTAINMENT];
    case EXPENSE_TYPE.PARKING:
      return EXPENSE_TYPE[EXPENSE_TYPE.PARKING];
    case EXPENSE_TYPE.SHOPPING:
      return EXPENSE_TYPE[EXPENSE_TYPE.SHOPPING];
    case EXPENSE_TYPE.CLOTHING:
      return EXPENSE_TYPE[EXPENSE_TYPE.CLOTHING];
    case EXPENSE_TYPE.MISC:
      return EXPENSE_TYPE[EXPENSE_TYPE.MISC];
    case EXPENSE_TYPE.GROCERIES:
      return EXPENSE_TYPE[EXPENSE_TYPE.GROCERIES];
    case EXPENSE_TYPE.HOUSING:
      return EXPENSE_TYPE[EXPENSE_TYPE.HOUSING];
    case EXPENSE_TYPE.UTILITIES:
      return EXPENSE_TYPE[EXPENSE_TYPE.UTILITIES];
    case EXPENSE_TYPE.INTERNET:
      return EXPENSE_TYPE[EXPENSE_TYPE.INTERNET];
    case EXPENSE_TYPE.PHONE:
      return EXPENSE_TYPE[EXPENSE_TYPE.PHONE];
    case EXPENSE_TYPE.HEALTHCARE:
      return EXPENSE_TYPE[EXPENSE_TYPE.HEALTHCARE];
    case EXPENSE_TYPE.INSURANCE:
      return EXPENSE_TYPE[EXPENSE_TYPE.INSURANCE];
    case EXPENSE_TYPE.SUBSCRIPTIONS:
      return EXPENSE_TYPE[EXPENSE_TYPE.SUBSCRIPTIONS];
    case EXPENSE_TYPE.TRAVEL:
      return EXPENSE_TYPE[EXPENSE_TYPE.TRAVEL];
    case EXPENSE_TYPE.GIFTS:
      return EXPENSE_TYPE[EXPENSE_TYPE.GIFTS];
    case EXPENSE_TYPE.FEES:
      return EXPENSE_TYPE[EXPENSE_TYPE.FEES];
    case EXPENSE_TYPE.ELECTRONICS:
      return EXPENSE_TYPE[EXPENSE_TYPE.ELECTRONICS];
    case EXPENSE_TYPE.HOBBIES:
      return EXPENSE_TYPE[EXPENSE_TYPE.HOBBIES];
    default:
      return EXPENSE_TYPE[EXPENSE_TYPE.MISC];
  }
};
